# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- beta

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: <SERVICE_CONNECTION_NAME>
    repository: <REPOSITORY_NAME>
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildNumber)

- task: AzureCLI@2
  inputs:
    azureSubscription: <SERVICE_CONNECTION_NAME>
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #!/bin/bash
                  az config set extension.use_dynamic_install=yes_without_prompt
                  az provider register --namespace Microsoft.App
                  az containerapp revision set-mode \
                    --name <CONTAINER_APP_NAME> \
                    --resource-group <RESOURCE_GROUP_NAME> \
                    --mode multiple
                  az containerapp revision label remove \
                    --name <CONTAINER_APP_NAME> \
                    --resource-group <RESOURCE_GROUP_NAME> \ 
                    --label teste-b
                  az containerapp update \
                    --name <CONTAINER_APP_NAME> \
                    --resource-group <RESOURCE_GROUP_NAME> \
                    --image crtdc.azurecr.io/tdcinnovation:'$(Build.BuildNumber)' \
                    --revision-suffix b'$(Build.BuildId)' 
                  az containerapp revision label add \
                    --revision <CONTAINER_APP_NAME>--b'$(Build.BuildId)' \
                    --resource-group <RESOURCE_GROUP_NAME> \
                    --label teste-b 
                  az containerapp ingress traffic set \
                    --name <CONTAINER_APP_NAME> \
                    --resource-group <RESOURCE_GROUP_NAME> \
                    --label-weight teste-a=80 teste-b=20
